# Generated by Django 4.2.5 on 2023-11-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_variation'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variation',
            field=models.ManyToManyField(blank=True, to='product.variation'),
        ),
    ]
